manifest = "3d67bfce9c1895f2b5838a9384f27bf34c919a3e1b64cefbcce1475d57244a87"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-exception"
target = "//:exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-regex"
target = "//:regex"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-unordered"
target = "//:unordered"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.52.0" ]
revision = "f2bd322d1a37a197efb4e17db90f3d19e6d80406"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.52.0" ]
revision = "d2db9edc46ccdf58e86d82ea9021abe62b1fab0b"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.52.0" ]
revision = "5a7dd9791a79355bedaca141c239cf7328177cc8"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.52.0" ]
revision = "2d6255b8fbd2eec649008975648d95311f698d21"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.52.0" ]
revision = "907f75cb7d1120daf4e882137574d0198448f3de"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.52.0" ]
revision = "572e0c8a71b21f0565676a3d4ff91814a8407027"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.52.0" ]
revision = "70d23360a96ffdc57a51177017b84ec045e379f0"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.52.0" ]
revision = "8c48422f180b40f40b628164fb851349d57f3dc1"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.52.0" ]
revision = "c31e05d0f3a1745b6305e2fa2bf6f78067c9283a"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.52.0" ]
revision = "b59839df5f163ce062737032cfa93542296675f7"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.52.0" ]
revision = "f566a486b9c9670bfe5e14d08eaf06f56ad0e511"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.52.0" ]
revision = "14db744d76f0697dd21f9433610563171e0629fd"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.52.0" ]
revision = "b26612245d8461fdf35482e38a52d3bba582ac59"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.52.0" ]
revision = "bbd74353a180d11588e21da34f824a43c7e5e402"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.52.0" ]
revision = "65b45d0d8119ed37a4829f29677e432d6a36b86c"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.52.0" ]
revision = "ea40e662719516c48040e643b3083c7776941ab6"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.52.0" ]
revision = "73d7072851f21805dbfd26cf68b69d473d889c00"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "1.52.0" ]
revision = "f36a8f8d1d35e0fce995d1b4c8b407fce7b61cad"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.52.0" ]
revision = "15edf9128ec0daaf34f92064585fe4d870897493"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.52.0" ]
revision = "5f6617c1b40228007ca57d7f3b011801fe0f6002"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.52.0" ]
revision = "e44f22f13d3047df7b3302f6f86164593181155d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.52.0" ]
revision = "f3e4e9ce56b3553e90055579e84c1b0738dbb25c"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.52.0" ]
revision = "c1cc7f79c391b2c09a59b13e8aff88a0b25c06a3"

[lock."github.com/buckaroo-pm/boost-unordered"]
versions = [ "1.52.0" ]
revision = "296fbceee49a1c9e2b5f43d72ac1555c3782c692"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.52.0" ]
revision = "8e193c2456cce1bd79c1525f2d1066b142bf9936"
