manifest = "6f7d4547d5d7d5b2c55241d4c1b4e8e3f7c849c21c43b533aed73ff4e5ea9b9c"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-exception"
target = "//:exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-regex"
target = "//:regex"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.34.0" ]
revision = "1e8f93d5a815fbea127cd9d8ea0cbdbb792d62af"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.34.0" ]
revision = "d9af2d82362cc350641992f2b93a304bbfd2f138"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.34.0" ]
revision = "1274c9a2aea715db35a4a19615aadc1b0f785302"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.34.0" ]
revision = "a826516fbfc9407906d7407d5efb9f0f849fed22"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.34.0" ]
revision = "8cc559cf9dd81cb4b78b9116f99b6f884719a2d3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.34.0" ]
revision = "708c06ea8f4330ce2221d5b2e53443dd6a480a2f"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.34.0" ]
revision = "bc573a3e55c934d8898158a8faf776aa1f73b706"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.34.0" ]
revision = "4775b46c2f61b77fb4b3940ada2921541494998d"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.34.0" ]
revision = "b3ce89a0bda80631f7764d94afe17d4f11dbcd8b"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.34.0" ]
revision = "45da1b73825ea9578ebf10ffb4d930971f4369fe"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.34.0" ]
revision = "619d0ed758b351f2abd8845c191787869931b088"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.34.0" ]
revision = "fdfd364ad468b1c0a2cbac72ca56b7dd47914815"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.34.0" ]
revision = "56d7c5af1f57a1f9225d43cfeb04fb1e315cdff9"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "1.34.0" ]
revision = "5633059b98e12011c2073dd6ba712e7fde2b910e"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.34.0" ]
revision = "3766ca5fadcf88ff0d0020d57d46a6d1591f0049"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.34.0" ]
revision = "a445c529654974ad6e292f62f98329c583416aba"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.34.0" ]
revision = "0730ab3ececa78a1fe9a9562542e2f0830412e7f"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.34.0" ]
revision = "6472cccaada6772fc6803a3373596d95bca56c0c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.34.0" ]
revision = "ff133d13498b91a2219c32ace9c8c27331cb38c7"
