manifest = "d43605fdcba4538513d2b5cac9ea155ac3d4cdbb350c65357f5c10beda91f7ac"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-exception"
target = "//:exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-regex"
target = "//:regex"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.35.0" ]
revision = "73cf0bdf8b0a5b38eb840951e4c0cfcd770a3f5b"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.35.0" ]
revision = "e07067dc90d1eac17cfa43b61c8b0abf4c510f65"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.35.0" ]
revision = "95165007aa5e95490580f43d1a6de9082eea7ea9"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.35.0" ]
revision = "a71e4983666230295b605f9ec2f0d00b5166498d"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.35.0" ]
revision = "fc394b0f8564682ddea46ba6d9d3785696452cbc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.35.0" ]
revision = "693fb62875f39d0ff647596c2a585dce0b80cc17"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.35.0" ]
revision = "4cbbec02833ec4af6a09daa569e9a06e6610989c"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.35.0" ]
revision = "9995b802d077e94e1af34b182b8fa531e8836b50"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.35.0" ]
revision = "d989fbc4b6b721bf088e4863048305740d016ab1"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.35.0" ]
revision = "84f29665d18034bb936fa14c9bb09ee191ddc82a"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.35.0" ]
revision = "5805ffb4e93476630edf5342685c2d864402d70e"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.35.0" ]
revision = "e91dd8b3dad1bf6663444aad6e1c79253c6584b4"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.35.0" ]
revision = "0e8f8d6f30f980c1b94b99f32acb27838871e96a"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "1.35.0" ]
revision = "40a484e4217395efb96b295488d1127e6ad649ad"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.35.0" ]
revision = "3378cc02d9541d38cfc9799c682315dd776c619a"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.35.0" ]
revision = "0e70c106c9c4dc55bb453228ea88e1b6fb282768"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.35.0" ]
revision = "35c13ee2e7eae41299a2a8edbd394da122ed1fc8"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.35.0" ]
revision = "2346ab26b335334e7ce8c6fbf37ba457d4fd44f3"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.35.0" ]
revision = "f8dfa2d706111d5f8483b160f67cb09a17da4485"
