manifest = "cafbd71363716348db44fd86189219446469c8c0db36491c8f1536735e3c88bd"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept-check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-exception"
target = "//:exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-regex"
target = "//:regex"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static-assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type-traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-unordered"
target = "//:unordered"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[[lock]]
name = "github.com/buckaroo-pm/boost-align"
version = "branch=master"
revision = "cb3c7a31931f9f02b3c663fa96f208c4f9055a44"

[[lock]]
name = "github.com/buckaroo-pm/boost-array"
version = "branch=master"
revision = "97b6d4fb6c67979c07d49f4f5dba444c70ec8889"

[[lock]]
name = "github.com/buckaroo-pm/boost-assert"
version = "branch=master"
revision = "cae7816110ba208a2290d02d128594e8809c9075"

[[lock]]
name = "github.com/buckaroo-pm/boost-concept_check"
version = "branch=master"
revision = "5a8bb5676742a02b9e2d343ecec66639da9deb3e"

[[lock]]
name = "github.com/buckaroo-pm/boost-config"
version = "branch=master"
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"

[[lock]]
name = "github.com/buckaroo-pm/boost-container_hash"
version = "branch=master"
revision = "9446eb516e717ae9c80bc89768a8d1160bcf6887"

[[lock]]
name = "github.com/buckaroo-pm/boost-core"
version = "branch=master"
revision = "10b589cb4aea4ca823237059f104cbfdd09b0f0e"

[[lock]]
name = "github.com/buckaroo-pm/boost-detail"
version = "branch=master"
revision = "94aa5268c1a74468be94b40afd730aea1730ceab"

[[lock]]
name = "github.com/buckaroo-pm/boost-exception"
version = "branch=master"
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[[lock]]
name = "github.com/buckaroo-pm/boost-function"
version = "branch=master"
revision = "1eca491e9ecb82359cb6346376554f057a7470d8"

[[lock]]
name = "github.com/buckaroo-pm/boost-integer"
version = "branch=master"
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[[lock]]
name = "github.com/buckaroo-pm/boost-iterator"
version = "branch=master"
revision = "c84fc34d0f6386edb15b0cb854a12864b6f15232"

[[lock]]
name = "github.com/buckaroo-pm/boost-move"
version = "branch=master"
revision = "183c4c120078cc80bdc9fd4089d911aecd922aac"

[[lock]]
name = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"
revision = "4c91f620f270414ceb5c3dbf3419a4f6ffe38c1e"

[[lock]]
name = "github.com/buckaroo-pm/boost-predef"
version = "branch=master"
revision = "73def0812b7235e0312079c729342787819bf1d5"

[[lock]]
name = "github.com/buckaroo-pm/boost-preprocessor"
version = "branch=master"
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[[lock]]
name = "github.com/buckaroo-pm/boost-range"
version = "branch=master"
revision = "bfbf1223a064828414338d293346bacfba5baacb"

[[lock]]
name = "github.com/buckaroo-pm/boost-regex"
version = "branch=master"
revision = "e32eb30f7653b835b20e7f578ab85962ee9bd0d5"

[[lock]]
name = "github.com/buckaroo-pm/boost-smart_ptr"
version = "branch=master"
revision = "360ba641a719a115373a2721b169086029fb4358"

[[lock]]
name = "github.com/buckaroo-pm/boost-static_assert"
version = "branch=master"
revision = "4b9da4628bc69ad0e9b244d3ec885f2eadac95d8"

[[lock]]
name = "github.com/buckaroo-pm/boost-throw_exception"
version = "branch=master"
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[[lock]]
name = "github.com/buckaroo-pm/boost-tuple"
version = "branch=master"
revision = "5f4b3f572603f796257652c6851af5a98f8a60a3"

[[lock]]
name = "github.com/buckaroo-pm/boost-type_traits"
version = "branch=master"
revision = "a34caf51f831ffb77d1057c668b5db620863d191"

[[lock]]
name = "github.com/buckaroo-pm/boost-unordered"
version = "branch=master"
revision = "3dc0b01d31125081942c05afa4b354a9011156ca"

[[lock]]
name = "github.com/buckaroo-pm/boost-utility"
version = "branch=master"
revision = "57aa216434800315c9cd2664169e444e3070a677"

[[lock]]
name = "github.com/buckaroo-pm/icu4c"
version = "branch=master"
revision = "d6803681f02ef9395665d4db6e84a4416a679bc3"
