manifest = "b2f3d749ceca0a1839211eacd1650333074e7d802d23c7e2a01fa2b77c31ab12"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept_check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-exception"
target = "//:exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-regex"
target = "//:regex"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.33.0" ]
revision = "d67ad2dbf578dd4648eadd30af3c36cf0384d947"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.33.0" ]
revision = "4b1c6be407ee5d2e3c2102884ce6cbe8a64f5d29"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.33.0" ]
revision = "d4adfbf5fc840b078d1da95ccf5b3cfc70a59bf0"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.0" ]
revision = "65a8650af82725f556021c523cb3a87f6b93c268"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.33.0" ]
revision = "49002478d20895d73b7ec88c9cbb96bf9e0c2085"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.0" ]
revision = "40ad58a6eec511d5c9b370e6316df7d27e2ed0ab"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.33.0" ]
revision = "108cc1a221c997b3e1f21a4814deec6c8d81a655"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.33.0" ]
revision = "9e60f69e3931e36c93a3d20f9e13883da21c64f9"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.33.0" ]
revision = "79ac7fe07fd054fe8f01ee37010f21b4ac221ea9"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.33.0" ]
revision = "68a0ed41855be989961e7a142ebe49571fb2e66c"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.33.0" ]
revision = "2e39fcead3918789936a1070f032fd677f1b98fb"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.33.0" ]
revision = "13db417fd9a81f2558365e854caf8d42a9100289"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.33.0" ]
revision = "ab4c920a85a064a78bed2e40cf2781723cbdc1e8"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "1.33.0" ]
revision = "c27784112c3d09ee04823a5d5ddce5a0d987af0f"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.33.0" ]
revision = "cf7d24fc38cb12f8431e9e6c3d05501a6c555e2a"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.33.0" ]
revision = "4acae7173fa1e199cb9bbe0d13bd447e60f5f23d"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.33.0" ]
revision = "5766cbb6edfb7db0c8962a9f8359801f33bf778a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.0" ]
revision = "18d5184bd19fe356de11b0a958a9134790d3ade8"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.33.0" ]
revision = "43f2eff4cf50a5fde6eaee135260bf7bd7bccb36"
